parameters:
    env(PIXABAY_KEY):
    env(UNSPLASH_ACCESS):
    aliases:
        author: post_author
        content: post_content
        date: post_date
        thumb: meta:_thumbnail_id
        title: post_title
        status: post_status
        template: meta:_wp_page_template
        excerpt: post_excerpt
        order: menu_order
    defaults:
        content: html:4,8,medium,ul,h2,h3
        date: date:4 months ago,now
        thumb: image:1600,1200,landscape,technology
        title: text:4,16
        status: publish
        author: ''
    acf_connections:
        image: image:1040,800,technology
        wysiwyg: html:4,short,ul,h2,h3
        text: text:4,16
        textarea: text:10,60
services:
    _defaults:
        autoconfigure: true
        public: false
    _instanceof:
        \Rdlv\WordPress\Dummy\CommandInterface:
            tags: ['app.command']
        \Rdlv\WordPress\Dummy\MetaCommandInterface:
            tags: ['app.meta_command']
        \Rdlv\WordPress\Dummy\HandlerInterface:
            tags: ['app.handler']
        \Rdlv\WordPress\Dummy\GeneratorInterface:
            tags: ['app.generator']
        \Rdlv\WordPress\Dummy\Initialized:
            tags: ['app.initialized']
        \Rdlv\WordPress\Dummy\UseFieldParserInterface:
            tags: ['app.use_field_parser']
    Rdlv\WordPress\Dummy\FieldParser:
        calls:
            - [set_aliases, ['%aliases%']]

    # generators
    identity:
        class: \Rdlv\WordPress\Dummy\Generator\Identity
    date:
        class: \Rdlv\WordPress\Dummy\Generator\RandomDate
    seqdate:
        class: \Rdlv\WordPress\Dummy\Generator\SequentialDate
    number:
        class: \Rdlv\WordPress\Dummy\Generator\RandomNumber
    html:
        class: \Rdlv\WordPress\Dummy\Generator\Loripsum
    image:
        class: \Rdlv\WordPress\Dummy\Generator\Unsplash
        calls:
            - [set_key, ['%env(UNSPLASH_ACCESS)%']]
#    pix:
#        class: \Rdlv\WordPress\Dummy\Pixabay
#        calls:
#            - [set_key, ['%env(PIXABAY_KEY)%']]
    text:
        class: \Rdlv\WordPress\Dummy\Generator\Wordipsum
    city:
        class: \Rdlv\WordPress\Dummy\Generator\SimpleMapsCity
    field:
        class: \Rdlv\WordPress\Dummy\Generator\PostFieldValue
    raw:
        class: \Rdlv\WordPress\Dummy\Generator\RawValue

    # handlers
    meta:
        class: \Rdlv\WordPress\Dummy\Handler\Meta
    acf:
        class: \Rdlv\WordPress\Dummy\Handler\Acf
        calls:
            - [set_connections, ['%acf_connections%']]

    # commands
    generate:
        class: \Rdlv\WordPress\Dummy\Command\Generate
        public: true
        calls:
            - [set_defaults, ['%defaults%']]
    clear:
        class: \Rdlv\WordPress\Dummy\Command\Clear
        public: true
    tasks:
        class: \Rdlv\WordPress\Dummy\Command\Tasks
        public: true
