<?php

/** @noinspection PhpDefineCanBeReplacedWithConstInspection */

/**
 * Do not edit this file. Edit the config files found in the config/ dir instead.
 * This file is required in the root directory so WordPress can find it.
 * WP is hardcoded to look in its own directory or one directory up for wp-config.php.
 */

/**
 * Allow WordPress to detect HTTPS when used behind a reverse proxy or a load balancer
 * See https://codex.wordpress.org/Function_Reference/is_ssl#Notes
 */
if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && in_array('https', explode(',', $_SERVER['HTTP_X_FORWARDED_PROTO']))) {
	$_SERVER['HTTPS'] = 'on';
}
if (empty($_SERVER['HTTPS'])) {
	$_SERVER['HTTPS'] = 'off';
}

/** Absolute path to the WordPress directory. */
define('CONTENT_DIR', '/app');
define('WP_CONTENT_DIR', __DIR__ . CONTENT_DIR);
define('WP_CONTENT_URL', ($_SERVER['HTTPS'] === 'on' ? 'https://' : 'http://') . $_SERVER['HTTP_HOST'] . CONTENT_DIR);


require_once dirname(__DIR__) . '/config.php';
require_once ABSPATH . '/wp-settings.php';
